[pytest]
# Opciones que se ejecutan automáticamente
addopts = -v --html=reports/report.html --self-contained-html

# Definición de markers
markers =
    smoke: pruebas críticas y rápidas
    api: pruebas de API
    ui: pruebas de interfaz